Repository AY2324S1-CS2103T-W08-3/tp, pull requests merged in 2023-11, with the labels that each got.

#90 Add UI for applications
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ApplyCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AppParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/contact/Organization.java
  src/main/java/seedu/address/model/jobapplication/JobApplication.java
  src/main/java/seedu/address/model/jobapplication/LastUpdatedTime.java
  src/main/java/seedu/address/storage/JsonAdaptedApplication.java
  src/main/java/seedu/address/storage/JsonAdaptedContact.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/ApplicationCard.java
  src/main/java/seedu/address/ui/ApplicationListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/ApplicationListCard.fxml
  src/main/resources/view/ApplicationListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AppParserTest.java
  src/test/java/seedu/address/model/jobapplication/JobApplicationTest.java
  src/test/java/seedu/address/storage/JsonAdaptedApplicationTest.java
Labels: type.Story, priority.High

#94 Fix issue with detecting duplicate contacts when adding
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/test/java/seedu/address/logic/commands/AddOrganizationCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddRecruiterCommandIntegrationTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: type.FeatureBug, severity.High

#97 Update autocomplete UI & UX
  src/main/java/seedu/address/logic/autocomplete/AutocompleteGenerator.java
  src/main/java/seedu/address/logic/parser/AppParser.java
  src/main/java/seedu/address/ui/AutocompleteTextField.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/autocomplete/AutocompleteGeneratorTest.java
Labels: type.FeatureBug, priority.Medium, severity.Medium

#96 Update message returned by commands
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: type.Enhancement, priority.Medium

#98 Implement update and delete application
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/autocomplete/data/AutocompleteConstraint.java
  src/main/java/seedu/address/logic/commands/DeleteApplicationCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditApplicationCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/contact/Organization.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteApplicationCommandTest.java
  src/test/java/seedu/address/logic/commands/EditApplicationCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: type.Story, priority.High

#100 Refactor AppParser to dynamically obtain results and fix autocomplete behaviour
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/parser/AppParser.java
  src/main/java/seedu/address/logic/parser/ClassMappings.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/ui/AutocompleteTextField.java
Labels: type.Chore, priority.Medium, severity.Medium

#99 Add DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation, type.Chore

#92 Update `SortCommand` functionality
  src/main/java/seedu/address/logic/commands/ReminderCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AppParser.java
  src/main/java/seedu/address/logic/parser/ClassMappings.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ReminderCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/jobapplication/JobApplication.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AppParserTest.java
  src/test/java/seedu/address/model/jobapplication/JobApplicationTest.java
Labels: type.Enhancement, priority.High

#103 Update Class Diagrams
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/apply-command/ApplyCommand.puml
  docs/diagrams/apply-command/style.puml
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/Ui.png
  docs/images/UiClassDiagram.png
  docs/images/apply-command/ApplyCommand.png
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/jobapplication/JobApplicationList.java
  src/test/java/seedu/address/model/jobapplication/JobApplicationListTest.java
Labels: type.Documentation, priority.Medium

#107 Update add recruiter UG
  docs/UserGuide.md
Labels: type.Documentation, priority.Low

#109 Update job application UI display
  src/main/java/seedu/address/model/jobapplication/LastUpdatedTime.java
  src/main/java/seedu/address/ui/ApplicationCard.java
Labels: type.Enhancement, priority.Medium

#106 Add DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#101 Update UG & DG with info about autocomplete
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ParserClasses.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ParserClasses.png
  docs/images/UiClassDiagram.png
  docs/images/autocomplete.png
Labels: type.Documentation, priority.High

#110 Add duplicate check for application
  src/main/java/seedu/address/logic/commands/ApplyCommand.java
  src/main/java/seedu/address/model/contact/Organization.java
  src/main/java/seedu/address/model/jobapplication/JobApplication.java
  src/test/java/seedu/address/model/jobapplication/JobApplicationTest.java
Labels: type.Enhancement, priority.Medium

#111 Update UG Edit and Find
  docs/UserGuide.md
Labels: type.Documentation

#112 Fix bug with `sort --none` input
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.FeatureBug, priority.Medium, severity.Medium

#105 Update DG for recruiter and rec-org link
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.Medium

#146 Remove redundant fields from `Organization`
  src/main/java/seedu/address/logic/commands/AddOrganizationCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/contact/Organization.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedContact.java
  src/main/java/seedu/address/ui/ContactCard.java
  src/main/resources/view/ContactListCard.fxml
  src/test/java/seedu/address/logic/commands/AddOrganizationCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddOrganizationCommandTest.java
  src/test/java/seedu/address/logic/commands/EditContactDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AppParserTest.java
  src/test/java/seedu/address/model/contact/OrganizationTest.java
  src/test/java/seedu/address/storage/JsonAdaptedContactTest.java
  src/test/java/seedu/address/testutil/EditContactDescriptorBuilder.java
  src/test/java/seedu/address/testutil/OrganizationBuilder.java
  src/test/java/seedu/address/testutil/TypicalContacts.java
Labels: type.Chore, priority.High

#149 Add structure for new UG
  docs/UserGuide.md
Labels: type.Documentation

#147 Change `Contact` and `AddCommand` classes to abstract
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/contact/Contact.java
  src/main/java/seedu/address/storage/JsonAdaptedContact.java
  src/test/data/JsonSerializableAddressBookTest/duplicateOrganizationAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateRecruiterAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ApplyCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteWithChildrenCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AppParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/contact/ContactTest.java
  src/test/java/seedu/address/model/contact/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/contact/OrganizationTest.java
  src/test/java/seedu/address/model/contact/RecruiterTest.java
  src/test/java/seedu/address/model/contact/UniqueContactListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedContactTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/ContactBuilder.java
  src/test/java/seedu/address/testutil/OrganizationBuilder.java
  src/test/java/seedu/address/testutil/RecruiterBuilder.java
  src/test/java/seedu/address/testutil/TypicalContacts.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Chore, priority.High

#148 Fix issue 143 and 144
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/contact/Organization.java
  src/main/java/seedu/address/model/jobapplication/JobApplication.java
  src/main/java/seedu/address/model/jobapplication/JobApplicationList.java
Labels: type.FeatureBug, priority.High, severity.Medium

#151 Add styles for difficulty and learning outcomes
  docs/assets/css/style.scss
Labels: type.Documentation, priority.Medium

#157 Update UG styling
  docs/assets/css/style.scss
Labels: type.Chore, priority.High

#156 Add documentation for add command
  docs/UserGuide.md
Labels: type.Documentation

#155 Add documentation for add recruiter command
  docs/UserGuide.md
  docs/images/add_recruiter_success.png
Labels: type.Documentation

#153 Add apply command documentation
  docs/UserGuide.md
Labels: type.Documentation

#152 Add UG QuickStart
  docs/UserGuide.md
  docs/images/starter-guide/add-application.jpg
  docs/images/starter-guide/add-john.jpg
  docs/images/starter-guide/add-woogle.jpg
  docs/images/starter-guide/delete-recursive.jpg
  docs/images/starter-guide/edit woogle.jpg
  docs/images/starter-guide/edit-application.jpg
  docs/images/starter-guide/edit-john.jpg
  docs/images/starter-guide/find-woogle.jpg
  docs/images/starter-guide/initial-ui.jpg
  docs/images/starter-guide/list.jpg
  docs/images/starter-guide/remind-earliest.jpg
Labels: type.Documentation, priority.High

#161 Add UG commands
  docs/UserGuide.md
Labels: type.Documentation

#162 Add `List` and `Sort` to UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ReminderCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
Labels: type.Documentation

#158 Fix ambiguous command behaviour
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: type.FeatureBug, priority.High, severity.Medium

#159 Improve code quality
  src/main/java/seedu/address/logic/commands/AddRecruiterCommand.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Chore, priority.Low

#166 Clear some tech debt
  src/main/java/seedu/address/logic/commands/ApplyCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/ApplyCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/contact/Organization.java
  src/main/java/seedu/address/model/contact/UniqueContactList.java
  src/main/java/seedu/address/storage/JsonAdaptedApplication.java
  src/main/java/seedu/address/ui/ApplicationListPanel.java
  src/main/java/seedu/address/ui/ContactListPanel.java
  src/test/java/seedu/address/storage/JsonAdaptedApplicationTest.java
Labels: type.Enhancement, severity.Low

#170 Add Wern PPP draft
  docs/team/wxwern.md
Labels: type.Documentation, priority.High

#168 Add planned enhancements to DG
  docs/DeveloperGuide.md
  docs/diagrams/enhancements/FlagChecker.puml
  docs/diagrams/enhancements/style.puml
  docs/diagrams/enhancements/warn.puml
  docs/diagrams/enhancements/warn_alt.puml
  docs/images/enhancements/FlagChecker.png
  docs/images/enhancements/formatting.png
  docs/images/enhancements/warn.png
  docs/images/enhancements/warn_alt.png
Labels: type.Documentation, priority.High

#171 Add CJ PPP draft
  docs/team/cj-lee01.md
Labels: type.Documentation, priority.High

#172 Add Bryan's PPP draft
  docs/team/mcnabry.md
Labels: type.Documentation

#164 Add Command Summary tables
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#169 Fix edit application command editing wrong index
  src/main/java/seedu/address/logic/commands/EditApplicationCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/jobapplication/Deadline.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/jobapplication/DeadlineTest.java
Labels: type.FeatureBug, priority.High, severity.Medium

#165 Update add recruiter UG
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#167 Improvements to website styling (incl. UG, DG, etc.)
  docs/UserGuide.md
  docs/_config.yml
  docs/_sass/minima/_base.scss
  docs/_sass/minima/_layout.scss
  docs/_sass/minima/custom-styles.scss
  docs/_sass/minima/initialize.scss
  docs/assets/css/style.scss
  docs/index.md
  docs/team/cj-lee01.md
  docs/team/mcnabry.md
  docs/team/tanshiyu1999.md
  docs/team/wamps-jp.md
  docs/team/wxwern.md
Labels: type.Enhancement, priority.Medium

#174 Update user stories
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#175 Update add org, find, edit, apply and delete
  docs/UserGuide.md
  docs/images/ug-images/labelled-gui.png
Labels: type.Documentation

#160 Fix sorting for JsonSerializableAddressBook to preserve Org-Rec hierarchy
  src/main/java/seedu/address/storage/JsonAdaptedContact.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateOrganizationAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateRecruiterAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
Labels: type.FeatureBug, priority.Medium

#173 Update `Organization`-`Recruiter` link in DG
  docs/DeveloperGuide.md
  docs/diagrams/AddRecruiterActivityDiagram.puml
  docs/images/AddRecruiterActivityDiagram.png
Labels: type.Documentation, priority.Medium

#176 Update UG
  docs/UserGuide.md
  docs/images/ug-images/labelled-gui.png
Labels: type.Documentation

#180 Fix edit bug for invalid id
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: type.FeatureBug, priority.High

#181 Refactor Person to Contact in DG
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: type.Documentation, priority.High

#184 Add more testing
  src/main/java/seedu/address/logic/commands/EditApplicationCommand.java
  src/test/java/seedu/address/logic/commands/ApplyCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteApplicationCommandTest.java
  src/test/java/seedu/address/logic/commands/EditApplicationCommandTest.java
  src/test/java/seedu/address/model/jobapplication/DeadlineTest.java
  src/test/java/seedu/address/testutil/OrganizationBuilder.java
  src/test/java/seedu/address/testutil/TypicalContacts.java
  src/test/java/seedu/address/testutil/TypicalJobApplications.java
Labels: priority.Medium

#182 Code fixes and cleanup
  docs/DeveloperGuide.md
  src/main/java/seedu/address/commons/core/Version.java
  src/main/java/seedu/address/commons/util/EnumUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/autocomplete/AutocompleteGenerator.java
  src/main/java/seedu/address/logic/autocomplete/AutocompleteSupplier.java
  src/main/java/seedu/address/logic/autocomplete/components/AutocompleteConstraint.java
  src/main/java/seedu/address/logic/autocomplete/components/AutocompleteItemSet.java
  src/main/java/seedu/address/logic/autocomplete/components/FlagValueSupplier.java
  src/main/java/seedu/address/logic/autocomplete/components/PartitionedCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ApplyCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ReminderCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AppParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/ClassMappings.java
  src/main/java/seedu/address/logic/parser/Flag.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/contact/Contact.java
  src/main/java/seedu/address/model/contact/Type.java
  src/main/java/seedu/address/model/contact/exceptions/InvalidContactTypeStringException.java
  src/main/java/seedu/address/model/jobapplication/ApplicationStage.java
  src/main/java/seedu/address/model/jobapplication/JobStatus.java
  src/main/java/seedu/address/storage/JsonAdaptedContact.java
  src/main/java/seedu/address/ui/AutocompleteTextField.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/ContactCard.java
  src/test/java/seedu/address/logic/autocomplete/AutocompleteGeneratorTest.java
  src/test/java/seedu/address/logic/autocomplete/AutocompleteSupplierTest.java
  src/test/java/seedu/address/logic/autocomplete/components/AutocompleteConstraintTest.java
  src/test/java/seedu/address/logic/parser/FlagTest.java
  src/test/java/seedu/address/model/jobapplication/ApplicationStageTest.java
  src/test/java/seedu/address/model/jobapplication/JobStatusTest.java
  src/test/java/seedu/address/storage/JsonAdaptedContactTest.java
Labels: type.FeatureBug, type.Chore, priority.Medium

#187 Remove data archiving
  docs/DeveloperGuide.md
Labels: type.Chore

#183 Add starter Guide
  docs/UserGuide.md
  docs/images/ug-images/app-added.png
  docs/images/ug-images/org-added.png
  docs/images/ug-images/rec-added.png
Labels: type.Documentation

#185 Update UG examples
  docs/UserGuide.md
  docs/images/sort_deadline.png
Labels: type.Documentation

#186 Change link to associate for add recruiter
  docs/UserGuide.md
Labels: type.Documentation, priority.Medium

#190 Add appendix for effort in DG
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#194 Add FAQ section
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#196 Update McNaBry's PPP
  docs/AboutUs.md
  docs/team/mcnabry.md
Labels: type.Documentation, priority.High

#193 Refactor UG
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#197 Refactor DG
  docs/DeveloperGuide.md
  docs/diagrams/enhancements/FlagChecker.puml
  docs/images/enhancements/FlagChecker.png
Labels: type.Documentation, priority.High

#198 Update DG and PPP
  docs/DeveloperGuide.md
  docs/diagrams/SortSequenceDiagram.puml
  docs/images/sort-command/SortCommand.png
  docs/team/wamps-jp.md
Labels: type.Documentation, priority.High

#201 Add test cases for `List`, `Sort`, and `Reminder`
  src/test/java/seedu/address/logic/commands/ReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ReminderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: type.Chore, severity.Low
