Repository AY2324S1-CS2103T-W08-3/tp, pull requests merged in 2023-10, with the labels that each got.

#8 Add self member info to AboutUs and PPP
  docs/AboutUs.md
  docs/images/wxwern.png
  docs/team/wxwern.md
Labels: type.Documentation

#21 Add items to .gitignore
  .gitignore
Labels: type.Chore

#19 Update UG to a skeleton of our new targets
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#24 Photo name change
  docs/AboutUs.md
  docs/images/tanshiyu1999.png
Labels: type.Chore

#25 Add terms to glossary
  docs/DeveloperGuide.md
Labels: type.Documentation

#26 Update generated project filenames and corresponding references
  build.gradle
  docs/UserGuide.md
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: type.Chore

#31 Refactor person to contact in diagrams, fixed previous refactor's NPE
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/tracing/LogicSequenceDiagram.puml
  src/main/resources/view/ContactListPanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, severity.High

#28 Refactor the "Prefix" class to "Flag", and update the defaults to match the Unix-like syntax "--flag"
  docs/UserGuide.md
  docs/diagrams/ParserClasses.puml
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/Flag.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/ContactUtil.java
Labels: type.Chore

#34 Add `Organization` class
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddOrganizationCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Contact.java
  src/main/java/seedu/address/model/person/Id.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Organization.java
  src/main/java/seedu/address/model/person/Position.java
  src/main/java/seedu/address/model/person/Status.java
  src/main/java/seedu/address/model/person/Type.java
  src/main/java/seedu/address/model/person/Url.java
  src/main/java/seedu/address/model/person/exceptions/InvalidContactTypeStringException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedContact.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/ContactTest.java
  src/test/java/seedu/address/storage/JsonAdaptedContactTest.java
  src/test/java/seedu/address/testutil/ContactBuilder.java
  src/test/java/seedu/address/testutil/ContactUtil.java
  src/test/java/seedu/address/testutil/TypicalContacts.java
Labels: type.Enhancement, priority.High

#37 Update UI to display Organization and Recruiter information
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/ui/ContactCard.java
  src/main/resources/view/ContactListCard.fxml
  src/main/resources/view/DarkTheme.css
Labels: type.Enhancement, priority.High

#32 Update delete contact functionality
  src/main/java/seedu/address/commons/exceptions/IllegalOperationException.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteWithChildrenCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Contact.java
  src/main/java/seedu/address/model/person/Organization.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Enhancement, priority.High

#38 Overhaul argument tokenization to be generic
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/Flag.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ArgumentMultimapTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/testutil/ContactUtil.java
Labels: type.Enhancement, priority.Medium

#44 Rename the app to Jobby
  README.md
  build.gradle
  docs/DeveloperGuide.md
  docs/Documentation.md
  docs/UserGuide.md
  docs/_config.yml
  docs/_data/projects.yml
  docs/_sass/minima/_base.scss
  docs/index.md
  docs/team/cj-lee01.md
  docs/team/mcnabry.md
  docs/team/tanshiyu1999.md
  docs/team/wamps-jp.md
  docs/team/wxwern.md
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/resources/view/MainWindow.fxml
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: type.Chore

#42 Make fields for `AddCommand` optional
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Contact.java
  src/main/java/seedu/address/model/person/Organization.java
  src/main/java/seedu/address/model/person/Recruiter.java
  src/main/java/seedu/address/model/person/Url.java
  src/main/java/seedu/address/storage/JsonAdaptedContact.java
  src/main/java/seedu/address/ui/ContactCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedContactTest.java
  src/test/java/seedu/address/testutil/ContactBuilder.java
  src/test/java/seedu/address/testutil/ContactUtil.java
  src/test/java/seedu/address/testutil/EditContactDescriptorBuilder.java
  src/test/java/seedu/address/testutil/RecruiterBuilder.java
Labels: type.Enhancement, priority.High

#43 Branch update organization
  src/main/java/seedu/address/logic/commands/AddOrganizationCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Organization.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedContact.java
  src/main/java/seedu/address/storage/JsonAdaptedId.java
  src/test/java/seedu/address/model/person/OrganizationTest.java
  src/test/java/seedu/address/storage/JsonAdaptedContactTest.java
  src/test/java/seedu/address/testutil/ContactBuilder.java
  src/test/java/seedu/address/testutil/OrganizationBuilder.java
  src/test/java/seedu/address/testutil/TypicalContacts.java
Labels: type.Enhancement, priority.High

#47 Update Add Command UG
  docs/UserGuide.md
Labels: type.Documentation, priority.Medium

#46 Update app UI, default data and relevant docs
  docs/images/Ui.png
  docs/index.md
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/ContactCard.java
  src/main/resources/view/ContactListCard.fxml
Labels: type.Documentation, type.Enhancement, priority.High

#49 Update UG and DG to include new command parsing info
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/ParserClasses.png
Labels: type.Documentation, priority.Medium

#52 Fix help window URL to point to our UG
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug, priority.High, severity.Medium

#50 Add RepoSense links, fix AboutUs, remove johndoe.md PPP template
  docs/AboutUs.md
  docs/team/cj-lee01.md
  docs/team/johndoe.md
  docs/team/mcnabry.md
  docs/team/tanshiyu1999.md
  docs/team/wamps-jp.md
  docs/team/wxwern.md
Labels: type.Documentation, priority.Medium

#51 Update `ListCommand` test cases and documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
Labels: type.Documentation, priority.High

#53 Update DG diagrams to reflect changes
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: type.Documentation, priority.Low

#45 Update Delete command UG, DG and messages
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: type.Documentation, priority.Medium

#54 Update codecov config
  .github/codecov.yml
Labels: type.Chore

#57 Change same contact to compare by id
  src/main/java/seedu/address/model/contact/Contact.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/contact/ContactTest.java
  src/test/java/seedu/address/model/contact/OrganizationTest.java
  src/test/java/seedu/address/model/contact/RecruiterTest.java
  src/test/java/seedu/address/storage/JsonAdaptedContactTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/EditContactDescriptorBuilder.java
  src/test/java/seedu/address/testutil/OrganizationBuilder.java
  src/test/java/seedu/address/testutil/RecruiterBuilder.java
  src/test/java/seedu/address/testutil/TypicalContacts.java
Labels: type.Chore

#61 Add flag alias support
  src/main/java/seedu/address/logic/parser/Flag.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/FlagTest.java
Labels: type.Enhancement, priority.Medium

#62 Improve `ArgumentMultimap`
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/test/java/seedu/address/logic/parser/ArgumentMultimapTest.java
Labels: type.Enhancement, priority.Low

#58 Implement Job application
  src/main/java/seedu/address/model/contact/Status.java
  src/main/java/seedu/address/model/jobapplication/ApplicationStage.java
  src/main/java/seedu/address/model/jobapplication/Deadline.java
  src/main/java/seedu/address/model/jobapplication/JobApplication.java
  src/main/java/seedu/address/model/jobapplication/JobDescription.java
  src/main/java/seedu/address/model/jobapplication/JobStatus.java
  src/main/java/seedu/address/model/jobapplication/JobTitle.java
  src/main/java/seedu/address/model/jobapplication/LastUpdatedTime.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/jobapplication/ApplicationStageTest.java
  src/test/java/seedu/address/model/jobapplication/DeadlineTest.java
  src/test/java/seedu/address/model/jobapplication/JobApplicationTest.java
  src/test/java/seedu/address/model/jobapplication/JobDescriptionTest.java
  src/test/java/seedu/address/model/jobapplication/JobStatusTest.java
  src/test/java/seedu/address/model/jobapplication/JobTitleTest.java
  src/test/java/seedu/address/model/jobapplication/LastUpdatedTimeTest.java
Labels: type.Epic, priority.Medium

#67 Update DG for Edit Command
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.Low, severity.Low

#71 Relax codecov for v1.3
  .github/codecov.yml
Labels: type.Chore, priority.High

#60 Implement linking of `Recruiter` to `Organization`
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddOrganizationCommand.java
  src/main/java/seedu/address/logic/commands/AddRecruiterCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/contact/Recruiter.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedContact.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddOrganizationCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddOrganizationCommandTest.java
  src/test/java/seedu/address/logic/commands/AddRecruiterCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddRecruiterCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AppParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/contact/RecruiterTest.java
  src/test/java/seedu/address/storage/JsonAdaptedContactTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/RecruiterBuilder.java
  src/test/java/seedu/address/testutil/TypicalContacts.java
Labels: type.Enhancement, priority.High

#59 Update Edit Function
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/contact/Id.java
  src/main/java/seedu/address/model/contact/Organization.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditContactDescriptorTest.java
  src/test/java/seedu/address/storage/JsonAdaptedContactTest.java
Labels: priority.Medium

#76 Update version number to 1.2.1
  .github/codecov.yml
  src/main/java/seedu/address/MainApp.java
Labels: priority.High

#82 Unify `INDEX/ID` preamble behavior from `edit` to `delete` and `apply`
  docs/UserGuide.md
  src/main/java/seedu/address/logic/autocomplete/AutocompleteGenerator.java
  src/main/java/seedu/address/logic/autocomplete/AutocompleteSupplier.java
  src/main/java/seedu/address/logic/autocomplete/FlagValueSupplier.java
  src/main/java/seedu/address/logic/autocomplete/PartitionedCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ApplyCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/ApplyCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/Flag.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/autocomplete/AutocompleteGeneratorTest.java
  src/test/java/seedu/address/logic/autocomplete/AutocompleteSupplierTest.java
  src/test/java/seedu/address/logic/parser/AppParserTest.java
  src/test/java/seedu/address/logic/parser/ApplyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Enhancement, priority.Medium

#84 Update `Id` to synthesize values based on names if it is omitted
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/contact/Id.java
  src/test/java/seedu/address/model/contact/IdTest.java
Labels: type.Enhancement, priority.Medium, severity.Medium, type.FeatureFlaw

#85 Improve badly-formatted and extraneous flag behavior
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/Flag.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/test/java/seedu/address/logic/parser/ApplyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/FlagTest.java
Labels: priority.Medium, severity.Medium, type.FeatureFlaw

#83 Edit FindCommand to parse name and id by substring
  src/main/java/seedu/address/model/contact/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/testutil/TypicalIds.java
Labels: priority.High, severity.High

#81 Add permanent storage for job applications
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/jobapplication/ApplicationStage.java
  src/main/java/seedu/address/model/jobapplication/JobApplication.java
  src/main/java/seedu/address/model/jobapplication/JobStatus.java
  src/main/java/seedu/address/model/jobapplication/LastUpdatedTime.java
  src/main/java/seedu/address/storage/JsonAdaptedApplication.java
  src/main/java/seedu/address/storage/JsonAdaptedContact.java
  src/test/java/seedu/address/storage/JsonAdaptedApplicationTest.java
  src/test/java/seedu/address/storage/JsonAdaptedContactTest.java
Labels: type.Story, priority.High

#88 Add support for "undoing" autocompleted terms
  src/main/java/seedu/address/ui/AutocompleteTextField.java
  src/main/java/seedu/address/ui/CommandBox.java
Labels: priority.Medium, severity.Medium, type.FeatureFlaw

#72 Add `SortCommand` functionality
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AppParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
Labels: priority.High
